services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pitchside
      POSTGRES_PASSWORD: pitchside
      POSTGRES_DB: pitchside_db
    ports:
      - "5432:5432"
    volumes:
      - pitchside_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pitchside_pg_data:
